import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head"; // Import Head
import Header from "@/_components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOM2X9p2gkzYwM5d8RvhfXJwZ3iI1NQ63vl1BBH"
          crossOrigin="anonymous"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen max-w-screen relative">
  <div className="max-w-[50vw] relative">
    <img
      src="/images/homeLeft.png"
      alt="Manakish Stories"
      className="min-h-full"
    />
    <div className="absolute top-[30px] left-[50px] w-[15vw] h-[5vw]">
      <img
        src="/images/Logo.png"
        alt="Manakish Stories"
        className="min-h-full"
      />
    </div>
  </div>
  <div className="w-[50vw] p-4">
    <Header/>
    {children}
  </div>
</div>
      </body>
    </html>
  );
}
